name: Build and deploy

on:
  push:
    branches: dev_env_ghc_wasm

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-dev_env:
    runs-on: macos-15-intel

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v16
        with:
          name: fanshi1028-personal
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build Dev Shell
        shell: nix develop .#wasm --command bash -e {0}
        run: |
          wasm32-wasi-ghc --version
          wasm32-wasi-cabal --version
          wasmtime --version
          wasi-sdk --version
